export const SET_IMAGE_LOADING = 'SET_IMAGE_LOADING';
export const SET_IMAGE_LOADING_DONE = 'SET_IMAGE_LOADING_DONE';
export const UPDATE_PRODUCT_IMAGE = 'UPDATE_PRODUCT_IMAGE';
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_DONE = 'SET_LOADING_DONE';
export const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST';